### PR TITLE
[WIP]: Trying to fix Windows CI

### PR DESCRIPTION
**Pull request by dfm**

### CODE REVIEW

**Comment by adrn** [comment]
Thanks for looking at this! These changes are probably good either way, but still seeing the same issue - weird

**Comment by adrn** [comment]
Hm, well I'm stumped. I tried pinning to a version of tox that previously worked, but now it's failing!

**Comment by dfm** [comment]
That's strange! I'm also stumped but I'll keep thinking about it and let you know if I come up with anything.

**Comment by adrn** [comment]
For future reference, here's a test run that worked:
https://github.com/adrn/gala/runs/1133584563?check_suite_focus=true

**Comment by adrn** [comment]
And see Pey Lian's response here: https://github.com/astropy/astropy/pull/10846#issuecomment-708015376

**Comment by adrn** [comment]
Apparently this issue is seen on travis w/ astropy windows builds that use conda. Also seen in photutils. From Pey Lian in Slack:

> I dunno... We already pinned miniconda in ci-helpers and their download site said they haven't changed miniconda installer since April 2019. But something has definitely changed with this tox + virtualenv + conda + CI combo

**Comment by adrn** [comment]
Aha! See issue here: https://github.com/ContinuumIO/anaconda-issues/issues/12094

**Pull request merged**
