### PR TITLE
adding STcovar

### PR DESCRIPTION
**Pull request by jngaravitoc**
### Checklist

* [ ] Did you add tests?
* [ ] Did you add documentation for your changes?
* [ ] Did you reference any relevant issues?
* [ ] Did you add a changelog entry? (see `CHANGES.rst`)
* [ ] Are the CI tests passing?
* [ ] Is the milestone set?

### CODE REVIEW

**Comment by jngaravitoc** [comment]
Hi @adrn I just added two test functions in test_computecoeff_discrete.py, one for coefficients_discrete and one for its variances including STvar.

**Comment by adrn** [comment]
Cool, thanks for this! 

Since the new functionality computes the off-diagonal term of a matrix, I wonder if we should instead return something that has shape `(nmax, lmax, mmax, 2, 2)` or `(2, 2, nmax, lmax, mmax)` and fill out the 2x2 matrix for each nlm combo?

**Comment by jngaravitoc** [comment]
Sorry for the late response! 

I think the off-diagonal terms would be the same for each nlm combo, since cov(S000, S001) = cov(S001,  S000). In that case, we might end up using extra memory?

**Comment by adrn** [comment]
That's right - it would use a little bit more memory, but it's just one duplicated element so it shouldn't be too bad! I think it is clearer to return a 2x2 array, so it would be worth the extra memory for me. But let me know what you think!

**Comment by jngaravitoc** [comment]
Switch to #252

**Pull request closed without merging**
