### PR TITLE
Remove adjust compiler to fix appveyor

### PR DESCRIPTION
**Pull request by bsipocz**
This causes a failure for appveyor, hopefully now there'll be an all green.

### CODE REVIEW

**Comment by bsipocz** [comment]
Also tries to fix the entry_points issue that came up in https://github.com/astropy/conda-channel-astropy/pull/85

**Comment by bsipocz** [comment]
Too bad, it was just a red-herring appveyor wise, but hopefully be enough to make the conda package build.

**Comment by adrn** [comment]
Thanks @bsipocz -- sorry I'm sucking, a bit swamped with other things right now.

**Comment by adrn** [comment]
@bsipocz Should I do a 0.1.3 release with this commit for the Conda build?

**Comment by bsipocz** [comment]
No problem. I'm just back from travelling and being overwhelmed with stuff,
too and quite badly started with the easy things so I can close tabs and
issues :)

**Comment by bsipocz** [comment]
Yes, I think that will work (except for windows, but that's an issue to solve for another day when you have time to figure out what goes wrong for the compiler).

**Pull request merged**
