### PR TITLE
Add better interaction with and export to sympy, and uses sympy to implement more Hessian functions

### LINKED ISSUE #5: Add Hessian functions for Cython potentials

### LINKED ISSUE #56: Potential classes should export to Sympy expressions

### LINKED ISSUE #85: Question on Hessian of potential
Hessian for potential $\Phi(\vec {r})$ is $\nabla\nabla \Phi$, i.e. ∂∂Φ/∂xi/∂xj right?

If I understand correctly,  `np.diag(om)` in 
```
class HarmonicOscillatorPotential(PotentialBase):
    ...
    def _hessian(self, q, t=0.):
        om = np.atleast_1d(self.parameters['omega'])
        return np.tile(np.diag(om)[:,:,None], reps=(1,1,q.shape[0]))
```
should be `np.diag(om*2)`?

Sorry if I missed anything obvious.

### LINKED ISSUE #159: Segfault and core dump on manipulating hessians
python 3.7
gala, numpy versions: 1.0, 1.16.4

I get core dump / seg fault from doing the follwing:
```python
import astropy.units as u
from gala.potential import BovyMWPotential2014

BovyMWPotential2014().hessian([[0, 8, 0]]*u.kpc)
```
Tracebacks: https://gist.github.com/smoh/0e803684b14d87bba4a97e5bb3e33bb0
1.out: beginning of errors from Red Hat
2.out: full traceback from Mac OSX 10.14.4

In both I did fresh install with conda
```sh
conda create -n gala-test
conda install -c conda-forge astro-gala
```
Any ideas?

### PR DESCRIPTION
**Pull request by adrn**
### Describe your changes

This adds a `.to_sympy()` classmethod to the potential classes. I've also then used this method with sympy to compute all of the Hessians, and implemented these using C code generated by sympy.

### Checklist

* [x] Did you add tests?
* [x] Did you add documentation for your changes?
* [x] Did you add a changelog entry? (see `CHANGES.rst`)
* [x] Are the CI tests passing?
* [x] Is the milestone set?

Amazingly, this closes #159, closes #56, closes #5, and closes #85 !!

### CODE REVIEW

**Comment by adrn** [comment]
cc @smoh - this finally fixes some of the Hessian issues you were having (...last year 😶)

**Comment by adrn** [comment]
Before merging, make an issue to remind me to figure out how to implement `to_sympy()` for `SCFPotential`

**Comment by smoh** [comment]
> cc @smoh - this finally fixes some of the Hessian issues you were having (...last year 😶)

Cool! Yea, I never got around to that.. That's a lot of tmps! 😅  Wouldn't it be neat if we could generate gradient funcs from sympy expression!

**Comment by adrn** [comment]
> That's a lot of tmps! 😅 

Heh, yea...at least they were auto-generated! 😄 

> Wouldn't it be neat if we could generate gradient funcs from sympy expression!

Do you mean in the same way that I generated the hessians, or you want to be able to create a potential class from an arbitrary sympy expression?

**Comment by smoh** [comment]
Oh, cool -- I missed this comment
```
/* Note: many Hessians generated with sympy in
    gala-notebooks/Make-all-Hessians.ipynb
*/
```

If you are autogenerating the C code from sympy, I guess you are already kind of doing it! Looking at it again, probably no sane person can stay on top of doing that by hand..!

And I see that you are comparing to the function generated using sympy's lambdify. I meant something like an integration with sympy's lambdify so that people can define e.g., potential by a symbolic expression, and any gradients would follow from sympy, too.

I'm actually curious how it was done in the notebook, which seems to be not available anywhere, specifically how you figured out the common factors to store in tmp variables. Is it a functionality sympy offers?

> > That's a lot of tmps! 😅
> 
> Heh, yea...at least they were auto-generated! 😄
> 
> > Wouldn't it be neat if we could generate gradient funcs from sympy expression!
> 
> Do you mean in the same way that I generated the hessians, or you want to be able to create a potential class from an arbitrary sympy expression?

**Comment by adrn** [comment]
> And I see that you are comparing to the function generated using sympy's lambdify. I meant something like an integration with sympy's lambdify so that people can define e.g., potential by a symbolic expression, and any gradients would follow from sympy, too.

Oh yea, that's a good idea! It would be a lot slower (unless I can figure out a way to combine with numba) but that would be cool. There's some limited support for this already, actually, but it could use some cleaning! https://gala-astro.readthedocs.io/en/latest/api/gala.potential.potential.from_equation.html#gala.potential.potential.from_equation

> I'm actually curious how it was done in the notebook, which seems to be not available anywhere, specifically how you figured out the common factors to store in tmp variables. Is it a functionality sympy offers?

It's a bit of a mess, but here it is: https://gist.github.com/e1aa71fbb11167d6109fb7077020d630

**Comment by smoh** [comment]
Thanks! That's pretty cool.

**Pull request merged**
