### PR TITLE
allow from_frame to be instance

### PR DESCRIPTION
**Pull request by nstarman**
so that transformation works on skyoffset frames.

Signed-off-by: Nathaniel Starkman <nstarkman@protonmail.com>

### Checklist

* [x] Did you add tests?  There currently are no tests for `get_transform_matrix`
* [x] Did you add documentation for your changes? yes
* [x] Did you reference any relevant issues? yes
* [ ] Did you add a changelog entry? (see `CHANGES.rst`)
* [x] Are the CI tests passing? yes
* [x] Is the milestone set?

### CODE REVIEW

**Comment by adrn** [comment]
Cool, this is a good idea -- thanks!

Could you add a simple test to `gala/coordinates/tests/test_pm_cov_transform.py` to check that this works with `SkyOffsetFrame`'s? I think all you need to do is add a `SkyOffsetFrame` instance to the list of parametrized tests, like:

```python
@pytest.mark.parametrize("to_frame", [coord.Galactic,
                                      coord.Supergalactic,
                                      OrphanKoposov19,
                                      SkyOffsetFrame(...)])
```

**Comment by adrn** [comment]
Looks good to me - thanks @nstarman!

**Comment by nstarman** [comment]
It would also be nice to have a function (or a flag in this one) that registers the transformation matrix into the frame transform graph. That would (marginally) speed up subsequent transformations and matrix computations.

**Comment by nstarman** [comment]
I was thinking something like `def get_transform_matrix(from_frame, to_frame, register=False):`

```
if register:
        coord.StaticMatrixTransform(M, from_frame_cls, to_frame_cls,
                                    register_graph=coord.frame_transform_graph)
        coord.StaticMatrixTransform(matrix_transpose(M), to_frame_cls, from_frame_cls,
                                    register_graph=coord.frame_transform_graph)

    return M
```

**Comment by adrn** [comment]
Hm, I'll have to think more about that - do you mean specifically for `SkyOffsetFrame`? I'm going to merge this - could you make a new issue about that idea?

**Pull request merged**
