### PR TITLE
Add the Magellanic Stream coordinate system.

### PR DESCRIPTION
**Pull request by DanielLenz**
Thanks for providing the gist in https://github.com/adrn/gala/issues/102, @adrn. I've done a few consistency checks, looks good!

### CODE REVIEW

**Comment by adrn** [comment]
Hi @DanielLenz - sorry for the slowness!

The travis builds are failing on Python 2.7 right now because of an annoying Numpy dependency issue, but it looks like the Python 3.x build are also failing because of a numpy formatting issue. In the docstring for `MagellanicStream`, I think you just need to change the expected output in the example to:
```
<MagellanicStream Coordinate: (L, B) in deg
    ( 359.86313884,  2.42583948)>
```

**Comment by adrn** [comment]
Otherwise, this looks good!

**Comment by DanielLenz** [comment]
Thanks @adrn ! I don't quite understand the issue with the doctest failure (see updates and travis fails to the PR), could you take a look/make an edit?

**Comment by adrn** [comment]
I'm going to merge this and deal with the style issues in a separate PR (#104 for future self). Thanks for this, @DanielLenz!

**Pull request merged**
